version: '3'

services:

  nginx:
    platform: linux/amd64
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - nodenet
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - db
      - app

  app:
    platform: linux/amd64
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh npm start
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - .docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge


  